name: "Terraform"

on:
  workflow_dispatch:
  push:
    branches:
      - "main"
    paths_ignore:
      - "*.md"
      - "Makefile"

jobs:
  terraform:
    runs-on: "ubuntu-22.04"
    steps:
      - id: "checkout"
        name: "Checkouts the Git repository"
        uses: "actions/checkout@v2"
      - id: "credential"
        name: "Setups the AWS credentials"
        uses: "aws-actions/configure-aws-credentials@v1"
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: "eu-west-1"
      - id: "terraform"
        name: "Installs the Terraform package"
        uses: "hashicorp/setup-terraform@v2"
        with:
          terraform_version: "v1.4.5"
      - id: "init"
        name: "Initializes the Terraform working directory"
        run: "terraform -chdir=terraform init"
      - id: "validate"
        name: "Validates the Terraform configuration"
        run: "terraform -chdir=terraform validate"
      - id: "plan"
        name: "Plans the Terraform infrastructure"
        run: "terraform -chdir=terraform plan -input=false"
