name: "Terraform"

on:
  workflow_dispatch:
  push:
    branches:
      - "main"
    paths_ignore:
      - "*.md"
      - "Makefile"

jobs:
  terraform:
    runs-on: "ubuntu-22.04"
    steps:
      - id: "checkout"
        name: "Checkouts the Git repository"
        uses: "actions/checkout@v2"
      - id: "terraform"
        name: "Installs the Terraform package"
        uses: "hashicorp/setup-terraform@v2"
        with:
          terraform_version: "v1.4.5"
      - id: "init"
        name: "Initializes the Terraform working directory"
        run: "terraform -chdir=terraform init"
      - id: "validate"
        name: "Validates the Terraform configuration"
        run: "terraform -chdir=terraform validate"
      - id: "plan"
        name: "Plans the Terraform infrastructure"
        run: "AWS_DEFAULT_REGION=$AWS_DEFAULT_REGION terraform -chdir=terraform plan -auto-approve -input=false"
        env:
          AWS_ACCESS_KEY_ID: "${{ secrets.AWS_ACCESS_KEY_ID }}"
          AWS_SECRET_ACCESS_KEY: "${{ secrets.AWS_SECRET_ACCESS_KEY }}"
          AWS_DEFAULT_REGION: "${{ env.AWS_DEFAULT_REGION }}"
